name: cron workflow

on:
  schedule:
    - cron: */5 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Testing cron steps
        run: echo "THIS IS FIRST CUSTOM GITHUB ACTIONS WORKFLOW FILE" 

