name: "Automatic"

on:
  push:
    branches:
      - main
env:
  USER_NAME: "kaalee"
  VARIABLE1: "var1"
  VARIABLE2: "var2"

    

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      VARIABLE1: "var1"
      VARIABLE2: "var3"
      
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Listing the contents on the repo
      run: ls -al  
    - name: Finding the owner and org of the repo
      run: |
        echo "$GITHUB_ACTOR"
        echo "$GITHUB_REPOSITORY"
        echo "$GITHUB_ACTION"
        echo "$GITHUB_WORKFLOW"
    - name: workflow variable
      run: echo "value of USER_NAME is $USER_NAME"
    - name: workflow variable
      run: echo "value of VARIABLE2 is $VARIABLE3" 

  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'karthi-ltim/test1' 
    #needs: build
    steps:
    - name: Deploy step
      run: echo "This is my first deploy step"
    - name: workflow variable
      run: echo "value of VARIABLE2 is $VARIABLE1"
    #- name: Viewing the content of sample1 file
    #  run: cat sample1.txt
