name: "Automatic"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Testing Manual workflow step
      run: echo "THIS IS FIRST CUSTOM GITHUB ACTIONS WORKFLOW FILE" 
    - name: Finding the owner and org of the repo
      run: |
        echo "$GITHUB_ACTOR"
        echo "$GITHUB_REPOSITORY"
        echo "$GITHUB_ACTION"
        echo "$GITHUB_WORKFLOW"

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy step
      run: echo "This is my first deploy step"
