name: "Automatic"

on:
  push:
    branches:
      - main
env:
  USER_NAME: "kaalee"
  VARIABLE1: "var1"
  VARIABLE2: "var2"

    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Listing the contents on the repo
      run: ls -al  
    - name: Finding the owner and org of the repo
      run: |
        echo "$GITHUB_ACTOR"
        echo "$GITHUB_REPOSITORY"
        echo "$GITHUB_ACTION"
        echo "$GITHUB_WORKFLOW"
    - name: workflow variable
      run: echo "value of USER_NAME is $USER_NAME" 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy step
      run: echo "This is my first deploy step"
    - name: workflow variable
      run: echo "value of VARIABLE1 is $VARIABLE1"
    #- name: Viewing the content of sample1 file
    #  run: cat sample1.txt
