name: "Manual"

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Testing Manual workflow step
      run: echo "THIS IS FIRST CUSTOM GITHUB ACTIONS WORKFLOW FILE" 
    - name: Finding the owner and org of the repo
      run: echo $GITHUB.ACTOR
